name: macOS build

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "desktop/**"

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: desktop/package-lock.json

      - name: Install deps
        working-directory: desktop
        run: npm ci

      - name: Make (Forge)
        working-directory: desktop
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crypto-auto-docs-mac
          path: |
            desktop/out/make/**/*.dmg
            desktop/out/make/**/*.zip
            desktop/out/**/mac-*/Crypto Auto Docs.app
